spring:
  # Datasource Configurations
  h2:
    console:
      enabled: true
      path: /h2-console

  # R2DBC Configuration
  r2dbc:
    url: r2dbc:h2:mem:///test_db
    username: sa
    password:
    initialization-mode: always
